<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CombatSkillSeeder extends Seeder
{
    public function run(): void
    {
        // Truncate or delete existing combat skills to reseed cleanly
        \Illuminate\Support\Facades\Schema::disableForeignKeyConstraints();
        DB::table('character_combat_skills')->truncate();
        DB::table('combat_skills')->truncate();
        \Illuminate\Support\Facades\Schema::enableForeignKeyConstraints();


        $skills = [
            // ==========================================
            // PRZEDZIAŁ 1: POZIOM 10 - 20 (WSTĘPNY)
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Mocny Cios',
                'description' => 'Potężne uderzenie mieczem, ignorujące część obrony. Zwiększa siłę ataku fizycznego.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 5,
                'base_duration' => 3,
                'base_value' => 0.20,
                'scaling_value' => 0.05,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'powerful-strike.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Rozłupanie',
                'description' => 'Miażdżący, zamaszysty atak toporem trafiający wszystkich przeciwników w grupie.',
                'type' => 'active',
                'required_weapon_type' => 'axe',
                'effect_type' => 'direct_dmg',
                'is_aoe' => true,
                'base_cooldown' => 4,
                'base_duration' => 1,
                'base_value' => 1.40,
                'scaling_value' => 0.15,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'cleave-axe.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Kula Ognia',
                'description' => 'Kula czystego magmy wywołująca podpalenie celu, zadające obrażenia zależne od maksymalnego HP.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'fire',
                'is_magic' => true,
                'base_cooldown' => 6,
                'base_duration' => 3,
                'base_value' => 0.02,
                'scaling_value' => 0.005,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'fireball.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Promień Światła',
                'description' => 'Święty błysk zaklinacza dzwonów, zadający natychmiastowe obrażenia magiczne.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'direct_dmg',
                'is_magic' => true,
                'base_cooldown' => 4,
                'base_duration' => 1,
                'base_value' => 1.30,
                'scaling_value' => 0.15,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'light-beam.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Trująca Strzała',
                'description' => 'Strzała powleczona jadem pająka. Zadaje obrażenia z upływem czasu równe procentowi aktualnego HP przeciwnika.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'poison',
                'base_cooldown' => 5,
                'base_duration' => 3,
                'base_value' => 0.05,
                'scaling_value' => 0.01,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'poison-arrow.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Szybkie Cięcie',
                'description' => 'Błyskawiczne pchnięcie sztyletem o niskim czasie odnowienia.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 3,
                'base_duration' => 1,
                'base_value' => 1.35,
                'scaling_value' => 0.15,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'quick-stab.png',
            ],

            // ==========================================
            // PRZEDZIAŁ 2: POZIOM 25 - 35 (ŚREDNI)
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Okrzyk Bojowy',
                'description' => 'Zastraszający okrzyk zwiększający siłę fizyczną bez względu na noszoną broń.',
                'type' => 'active',
                'required_weapon_type' => 'all',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 7,
                'base_duration' => 4,
                'base_value' => 0.30,
                'scaling_value' => 0.05,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'battle-cry.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Wirujący Miecz',
                'description' => 'Pełny obrót miecza zadający wysokie obrażenia wszystkim wrogom dookoła.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'direct_dmg',
                'is_aoe' => true,
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 1.80,
                'scaling_value' => 0.20,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'whirlwind-sword.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Lodowy Pocisk',
                'description' => 'Lodowy promień zamrażający cel i zadający potężne obrażenia bezpośrednie.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'direct_dmg',
                'is_magic' => true,
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 1.70,
                'scaling_value' => 0.20,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'ice-bolt.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Błogosławieństwo Szamana',
                'description' => 'Rytualna pieśń zwięszająca siłę duchową i obrażenia bojowe.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'buff_phys_dmg',
                'is_magic' => true,
                'base_cooldown' => 7,
                'base_duration' => 3,
                'base_value' => 0.25,
                'scaling_value' => 0.05,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'shaman-blessing.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Ognista Strzała',
                'description' => 'Płonąca strzała zadająca obrażenia na podstawie maksymalnego HP przeciwnika.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'fire',
                'base_cooldown' => 7,
                'base_duration' => 3,
                'base_value' => 0.03,
                'scaling_value' => 0.01,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'fire-arrow.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Zatruty Sztylet',
                'description' => 'Wykonywany z zaskoczenia cios zatrutym ostrzem rozlewający jad w ciele wroga.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'poison',
                'base_cooldown' => 5,
                'base_duration' => 4,
                'base_value' => 0.06,
                'scaling_value' => 0.01,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'poison-dagger.png',
            ],

            // ==========================================
            // PRZEDZIAŁ 3: POZIOM 45 - 55 (ZAAWANSOWANY)
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Miażdżące Cięcie',
                'description' => 'Rozpalony topór nakłada głębokie krwawienie i podpalenie na cel.',
                'type' => 'active',
                'required_weapon_type' => 'axe',
                'effect_type' => 'fire',
                'base_cooldown' => 6,
                'base_duration' => 3,
                'base_value' => 0.035,
                'scaling_value' => 0.01,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'crushing-axe.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Szarża Rycerska',
                'description' => 'Niszczycielski wypad miecza z pełną siłą rozpędu.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 2.40,
                'scaling_value' => 0.25,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'knight-charge.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Piekielny Pożar',
                'description' => 'Rozpętanie płomieni ognia piekielnego pożerającego żywotność wroga.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'fire',
                'is_magic' => true,
                'base_cooldown' => 8,
                'base_duration' => 4,
                'base_value' => 0.045,
                'scaling_value' => 0.01,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'hellfire.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Dzwon Przeznaczenia',
                'description' => 'Rezonujący gong rozbijający pancerz i zadający krytyczne obrażenia magiczne.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'direct_dmg',
                'is_magic' => true,
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 2.40,
                'scaling_value' => 0.25,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'destiny-bell.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Grad Strzał',
                'description' => 'Salwa strzał wypuszczona z niewiarygodną prędkością, zasypująca wszystkich wrogów w grupie.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'direct_dmg',
                'is_aoe' => true,
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 2.30,
                'scaling_value' => 0.25,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'arrow-rain.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Cios w Plecy',
                'description' => 'Zabójcze ukłucie w czuły punkt celu z zadaniem gigantycznych obrażeń.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 4,
                'base_duration' => 1,
                'base_value' => 2.60,
                'scaling_value' => 0.30,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'backstab.png',
            ],

            // ==========================================
            // PRZEDZIAŁ 4: POZIOM 60 - 75 (EKSPERCJI)
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Gniew Berserkera',
                'description' => 'Wpadnięcie w szał bitewny dramatycznie zwiększający zadawane obrażenia.',
                'type' => 'active',
                'required_weapon_type' => 'axe',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 8,
                'base_duration' => 4,
                'base_value' => 0.50,
                'scaling_value' => 0.08,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'berserker-rage.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Smoczy Zamach',
                'description' => 'Cięcie nasycone smoczą energią, ignorujące defensywę przeciwnika.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 3.20,
                'scaling_value' => 0.30,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'dragon-slash.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Piorun Arcymaga',
                'description' => 'Piorun uderzający prosto z niebios w wybranego przeciwnika.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'direct_dmg',
                'is_magic' => true,
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 3.30,
                'scaling_value' => 0.30,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'lightning-strike.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Święta Aura',
                'description' => 'Aura czystej mocy bojowej wzmacniająca ataki o znaczny procent.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'buff_phys_dmg',
                'is_magic' => true,
                'base_cooldown' => 9,
                'base_duration' => 4,
                'base_value' => 0.50,
                'scaling_value' => 0.08,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'holy-aura.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Precyzyjny Strzał w Serce',
                'description' => 'Strzał mierzony prosto w prosto w serce z dewastującą siłą.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 3.40,
                'scaling_value' => 0.35,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'heart-shot.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Taniec Cieni',
                'description' => 'Wykonywana sekwencja mrocznych cięć podnosząca skuteczność ataku.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 7,
                'base_duration' => 3,
                'base_value' => 0.60,
                'scaling_value' => 0.10,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'shadow-dance.png',
            ],

            // ==========================================
            // PRZEDZIAŁ 5: POZIOM 80 - 90 (MISTRZOWSKI)
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Żelazny Bastion',
                'description' => 'Zwycięska postawa bojowa podnosząca siłę i skupienie ataku na najwyższy poziom.',
                'type' => 'active',
                'required_weapon_type' => 'all',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 9,
                'base_duration' => 5,
                'base_value' => 0.70,
                'scaling_value' => 0.10,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'iron-bastion.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Piekielne Cięcie',
                'description' => 'Atak bronią białą pozostawiający niegasnące płomienie zagłady.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'fire',
                'base_cooldown' => 7,
                'base_duration' => 4,
                'base_value' => 0.06,
                'scaling_value' => 0.015,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'infernal-slash.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Meteoryt Mroku',
                'description' => 'Przyzwanie kosmicznego skału mroku spalającego maksymalne zdrowie wroga.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'fire',
                'is_magic' => true,
                'base_cooldown' => 9,
                'base_duration' => 4,
                'base_value' => 0.07,
                'scaling_value' => 0.015,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'dark-meteor.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Promień Zagłady',
                'description' => 'Skupiony snop kosmicznej energii dzwonu zmiatający wszystkich przeciwników na swojej drodze.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'direct_dmg',
                'is_magic' => true,
                'is_aoe' => true,
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 4.20,
                'scaling_value' => 0.40,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'beam-doom.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Deszcz Jadowitych Strzał',
                'description' => 'Chmura jadowitych bełtów trawiąca zdrowie aktualne celów z ogromną siłą.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'poison',
                'base_cooldown' => 8,
                'base_duration' => 4,
                'base_value' => 0.12,
                'scaling_value' => 0.02,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'venom-rain.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Zabójczy Cień',
                'description' => 'Mordercze pchnięcie prosto ze świata cieni.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 4.40,
                'scaling_value' => 0.45,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'fatal-shadow.png',
            ],

            // ==========================================
            // PRZEDZIAŁ 6: POZIOM 95 - 99 (LEGENDARNY)
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Cios Rozdzierający Światy',
                'description' => 'Niewyobrażalny zamach rozcinający czasoprzestrzeń i zadający gigantyczne obrażenia.',
                'type' => 'active',
                'required_weapon_type' => 'axe',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 7,
                'base_duration' => 1,
                'base_value' => 5.50,
                'scaling_value' => 0.50,
                'required_level' => 95,
                'unlock_cost' => 80,
                'icon' => 'world-render.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Ostateczna Obrona Boska',
                'description' => 'Błogosławieństwo bogów wojny dające gigantyczny wzrost mocy bojowej.',
                'type' => 'active',
                'required_weapon_type' => 'all',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 10,
                'base_duration' => 5,
                'base_value' => 1.00,
                'scaling_value' => 0.15,
                'required_level' => 95,
                'unlock_cost' => 80,
                'icon' => 'divine-bastion.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Apokalipsa Elementów',
                'description' => 'Kompletne zniszczenie żywiołami powodujące absolutne spopielenie wroga.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'fire',
                'is_magic' => true,
                'base_cooldown' => 10,
                'base_duration' => 5,
                'base_value' => 0.09,
                'scaling_value' => 0.02,
                'required_level' => 99,
                'unlock_cost' => 100,
                'icon' => 'elemental-apocalypse.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Boska Światłość',
                'description' => 'Pierwotne światło niszczące mrok i odparowujące przeciwnika.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'direct_dmg',
                'is_magic' => true,
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 6.00,
                'scaling_value' => 0.60,
                'required_level' => 99,
                'unlock_cost' => 100,
                'icon' => 'divine-light.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Boski Strzał Arcyłowcy',
                'description' => 'Mityczny strzał ostateczny przewiercający wszystko na swojej drodze.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 5.80,
                'scaling_value' => 0.55,
                'required_level' => 99,
                'unlock_cost' => 100,
                'icon' => 'god-shot.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Ostrze Pustki',
                'description' => 'Legendarne cięcie mrokiem trawiące żywotność i kwas przeciwnika z niewyobrażalną siłą.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'poison',
                'base_cooldown' => 7,
                'base_duration' => 5,
                'base_value' => 0.15,
                'scaling_value' => 0.025,
                'required_level' => 99,
                'unlock_cost' => 100,
                'icon' => 'void-blade.png',
            ],

            // ==========================================
            // PRZEDZIAŁ DODATKOWY: ROZBUDOWA SYSTEMU (2026-07-28)
            // Obszarówki (AoE) pod grupy potworów, obrażenia magiczne (Różdżka/Dzwon),
            // leczenie, zamrożenie/ogłuszenie oraz pasywy (aura obrażeń, dodatkowy atak).
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Rozproszenie Strzał',
                'description' => 'Łucznik wypuszcza wachlarz strzał, trafiając wszystkich przeciwników w grupie naraz.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'aoe_dmg',
                'is_aoe' => true,
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 1.10,
                'scaling_value' => 0.10,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'arrow-spread.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Stały Refleks',
                'description' => 'Pasywny refleks łucznika - każde trafienie ma szansę na natychmiastowy dodatkowy strzał.',
                'type' => 'passive',
                'required_weapon_type' => 'bow',
                'effect_type' => 'passive_extra_attack',
                'base_cooldown' => 0,
                'base_duration' => 0,
                'base_value' => 0.12,
                'scaling_value' => 0.02,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'steady-reflex.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Ognisty Grad',
                'description' => 'Deszcz kul ognia spadający z nieba, obejmujący swoim zasięgiem całą grupę przeciwników.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'aoe_dmg',
                'is_magic' => true,
                'is_aoe' => true,
                'base_cooldown' => 7,
                'base_duration' => 1,
                'base_value' => 1.05,
                'scaling_value' => 0.10,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'fire-hail.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Lodowe Okowy',
                'description' => 'Mroźny pocisk zadający obrażenia i zamrażający cel, odbierając mu turę ataku.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'freeze',
                'is_magic' => true,
                'base_cooldown' => 8,
                'base_duration' => 2,
                'base_value' => 1.10,
                'scaling_value' => 0.15,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'icy-shackles.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Rezerwy Astralne',
                'description' => 'Pasywny, stale utrzymujący się napływ astralnej mocy zwiększający obrażenia magiczne.',
                'type' => 'passive',
                'required_weapon_type' => 'wand',
                'effect_type' => 'passive_aura_dmg',
                'is_magic' => true,
                'base_cooldown' => 0,
                'base_duration' => 0,
                'base_value' => 0.18,
                'scaling_value' => 0.03,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'astral-reserves.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Ogłuszający Cios',
                'description' => 'Potężne uderzenie rękojeścią miecza w skroń, ogłuszające przeciwnika na turę.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'stun',
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 1.20,
                'scaling_value' => 0.15,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'stunning-blow.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Aura Miecza',
                'description' => 'Ostrze wojownika spowija stała aura mocy, zwiększająca obrażenia fizyczne każdego ataku.',
                'type' => 'passive',
                'required_weapon_type' => 'sword',
                'effect_type' => 'passive_aura_dmg',
                'base_cooldown' => 0,
                'base_duration' => 0,
                'base_value' => 0.15,
                'scaling_value' => 0.03,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'sword-aura.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Roztrzaskujące Uderzenie',
                'description' => 'Miażdżący cios toporem w kolana przeciwnika, ogłuszający go na turę.',
                'type' => 'active',
                'required_weapon_type' => 'axe',
                'effect_type' => 'stun',
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 1.25,
                'scaling_value' => 0.15,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'smashing-blow.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Furia Berserkera',
                'description' => 'Pasywny szał bitewny - każdy cios toporem ma szansę na natychmiastowy dodatkowy atak.',
                'type' => 'passive',
                'required_weapon_type' => 'axe',
                'effect_type' => 'passive_extra_attack',
                'base_cooldown' => 0,
                'base_duration' => 0,
                'base_value' => 0.15,
                'scaling_value' => 0.03,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'berserker-fury.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Pieśń Odnowy',
                'description' => 'Kojący dźwięk dzwonu lecząca ranę zamiast atakować, przywracając część maksymalnego HP.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'heal',
                'is_magic' => true,
                'base_cooldown' => 8,
                'base_duration' => 1,
                'base_value' => 0.25,
                'scaling_value' => 0.05,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'song-of-renewal.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Boskie Uzdrowienie',
                'description' => 'Potężny akord uzdrawiający, przywracający znaczną część maksymalnego HP postaci.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'heal',
                'is_magic' => true,
                'base_cooldown' => 9,
                'base_duration' => 1,
                'base_value' => 0.40,
                'scaling_value' => 0.06,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'divine-healing.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Rezonans Wiary',
                'description' => 'Pasywny rezonans świętej mocy dzwonu, stale zwiększający siłę zadawanych obrażeń.',
                'type' => 'passive',
                'required_weapon_type' => 'bell',
                'effect_type' => 'passive_aura_dmg',
                'is_magic' => true,
                'base_cooldown' => 0,
                'base_duration' => 0,
                'base_value' => 0.22,
                'scaling_value' => 0.04,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'faith-resonance.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Wir Ostrzy',
                'description' => 'Błyskawiczny obrót z dwoma sztyletami, tnący wszystkich przeciwników w zasięgu.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'aoe_dmg',
                'is_aoe' => true,
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 1.15,
                'scaling_value' => 0.12,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'blade-flurry.png',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Cichy Krok',
                'description' => 'Pasywna zwinność skrytobójcy - każde ukłucie ma szansę na natychmiastowy dodatkowy cios.',
                'type' => 'passive',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'passive_extra_attack',
                'base_cooldown' => 0,
                'base_duration' => 0,
                'base_value' => 0.13,
                'scaling_value' => 0.02,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'silent-step.png',
            ],
            // ==========================================
            // PRZEDZIAŁ DODATKOWY 2: RÓWNOWAGA TYPÓW (2026-07-29)
            // Dobudowuje słabo obsadzone kategorie bez ruszania istniejących
            // skilli: leczenie na każdym przedziale poziomowym (nie tylko
            // 25/60), AOE tam gdzie go dotąd zabrakło (10/60/95-99),
            // crowd control (freeze/stun) na 10/60/80/99, trucizna/podpalenie
            // na poziomie 60 oraz zupełnie nowa kategoria Obrony
            // (`buff_defense` - redukcja obrażeń przychodzących o % na X tur,
            // patrz docs/modules/skills.md pkt. 5).
            // ==========================================

            // --- Leczenie (Dzwon) na przedziałach, gdzie go dotąd nie było ---
            [
                'id' => Str::ulid(),
                'name' => 'Kojący Dźwięk',
                'description' => 'Delikatny rezonans dzwonu koją rany, przywracając niewielką część zdrowia.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'heal',
                'is_magic' => true,
                'base_cooldown' => 7,
                'base_duration' => 1,
                'base_value' => 0.15,
                'scaling_value' => 0.03,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'soothing-tone.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Chór Uzdrowienia',
                'description' => 'Wielogłosowy śpiew wspierający regenerację, przywracający znaczącą część zdrowia.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'heal',
                'is_magic' => true,
                'base_cooldown' => 8,
                'base_duration' => 1,
                'base_value' => 0.32,
                'scaling_value' => 0.055,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'healing-chorus.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Hymn Świętej Odnowy',
                'description' => 'Potężny hymn kapłański przywracający dużą część maksymalnego zdrowia.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'heal',
                'is_magic' => true,
                'base_cooldown' => 9,
                'base_duration' => 1,
                'base_value' => 0.50,
                'scaling_value' => 0.07,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'sacred-renewal-hymn.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Requiem Wskrzeszenia',
                'description' => 'Ostateczna pieśń kapłana przywracająca niemal całe utracone zdrowie.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'heal',
                'is_magic' => true,
                'base_cooldown' => 10,
                'base_duration' => 1,
                'base_value' => 0.65,
                'scaling_value' => 0.08,
                'required_level' => 99,
                'unlock_cost' => 100,
                'icon' => 'resurrection-requiem.png',
                'icon' => null,
            ],

            // --- AOE tam, gdzie dotąd nie było żadnej opcji obszarowej ---
            [
                'id' => Str::ulid(),
                'name' => 'Fala Uderzeniowa',
                'description' => 'Wybuch czystej energii magicznej rozchodzący się na wszystkich przeciwników w starciu.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'aoe_dmg',
                'is_magic' => true,
                'is_aoe' => true,
                'base_cooldown' => 7,
                'base_duration' => 1,
                'base_value' => 1.00,
                'scaling_value' => 0.10,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'shockwave.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Podwójne Cięcie',
                'description' => 'Błyskawiczny podwójny zamach sztyletami trafiający wszystkich wrogów w zasięgu.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'aoe_dmg',
                'is_aoe' => true,
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 1.05,
                'scaling_value' => 0.10,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'double-slash.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Trzęsienie Ziemi',
                'description' => 'Uderzenie toporem w ziemię wywołujące falę wstrząsów pod wszystkimi przeciwnikami.',
                'type' => 'active',
                'required_weapon_type' => 'axe',
                'effect_type' => 'aoe_dmg',
                'is_aoe' => true,
                'base_cooldown' => 7,
                'base_duration' => 1,
                'base_value' => 1.60,
                'scaling_value' => 0.15,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'earthquake.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Świetlisty Krąg',
                'description' => 'Krąg oślepiającego światła rozchodzący się z dzwonu, raniący wszystkich wrogów.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'aoe_dmg',
                'is_magic' => true,
                'is_aoe' => true,
                'base_cooldown' => 7,
                'base_duration' => 1,
                'base_value' => 1.55,
                'scaling_value' => 0.15,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'luminous-circle.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Zagłada Ostrzy',
                'description' => 'Seria druzgocących cięć mieczem obejmująca całą grupę przeciwników naraz.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'aoe_dmg',
                'is_aoe' => true,
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 2.60,
                'scaling_value' => 0.25,
                'required_level' => 99,
                'unlock_cost' => 80,
                'icon' => 'blade-doomsday.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Deszcz Zniszczenia',
                'description' => 'Ostateczna salwa strzał zasypująca całe pole bitwy, raniąca wszystkich wrogów.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'aoe_dmg',
                'is_aoe' => true,
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 2.70,
                'scaling_value' => 0.25,
                'required_level' => 99,
                'unlock_cost' => 100,
                'icon' => 'destruction-rain.png',
                'icon' => null,
            ],

            // --- Crowd Control (freeze/stun) na przedziałach, gdzie go dotąd nie było ---
            [
                'id' => Str::ulid(),
                'name' => 'Mroźny Podmuch',
                'description' => 'Lodowaty powiew różdżki spowalniający i raniący przeciwnika już od pierwszych starć.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'freeze',
                'is_magic' => true,
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 1.05,
                'scaling_value' => 0.10,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'frost-gust.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Paraliżujący Strzał',
                'description' => 'Strzała trafiająca w splot nerwowy, na chwilę odbierająca przeciwnikowi możliwość ataku.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'stun',
                'base_cooldown' => 7,
                'base_duration' => 2,
                'base_value' => 1.90,
                'scaling_value' => 0.20,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'paralyzing-shot.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Okowy Cienia',
                'description' => 'Mroczne pęta ze sztyletu oplatające przeciwnika i unieruchamiające go na kilka tur.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'freeze',
                'base_cooldown' => 7,
                'base_duration' => 2,
                'base_value' => 2.20,
                'scaling_value' => 0.22,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'shadow-shackles.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Wieczny Chłód',
                'description' => 'Absolutne zero przywołane różdżką, zamrażające przeciwnika na długie tury.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'freeze',
                'is_magic' => true,
                'base_cooldown' => 8,
                'base_duration' => 2,
                'base_value' => 3.00,
                'scaling_value' => 0.30,
                'required_level' => 99,
                'unlock_cost' => 100,
                'icon' => 'absolute-zero.png',
                'icon' => null,
            ],

            // --- Trucizna / Podpalenie na poziomie 60 (dotąd zero DoT-ów w tym przedziale) ---
            [
                'id' => Str::ulid(),
                'name' => 'Żrący Jad',
                'description' => 'Zaawansowana mikstura trucizny wtapiająca się w ranę i trawiąca zdrowie wroga.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'poison',
                'base_cooldown' => 6,
                'base_duration' => 4,
                'base_value' => 0.09,
                'scaling_value' => 0.015,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'caustic-venom.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Płonący Impet',
                'description' => 'Rozgrzane do czerwoności ostrze pozostawiające na ciele wroga tlące się rany.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'fire',
                'base_cooldown' => 7,
                'base_duration' => 3,
                'base_value' => 0.05,
                'scaling_value' => 0.012,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'burning-impetus.png',
                'icon' => null,
            ],

            // --- Obrona: zupełnie nowa kategoria (buff_defense), po jednym skillu na broń ---
            [
                'id' => Str::ulid(),
                'name' => 'Postawa Tarczy',
                'description' => 'Defensywna postawa wojownika mieczem, redukująca obrażenia przychodzące przez kilka tur.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'buff_defense',
                'base_cooldown' => 6,
                'base_duration' => 3,
                'base_value' => 0.15,
                'scaling_value' => 0.03,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'shield-stance.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Żelazna Skóra',
                'description' => 'Napięcie mięśni i skupienie berserkera utwardzające skórę niczym stal.',
                'type' => 'active',
                'required_weapon_type' => 'axe',
                'effect_type' => 'buff_defense',
                'base_cooldown' => 7,
                'base_duration' => 3,
                'base_value' => 0.18,
                'scaling_value' => 0.03,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'iron-skin.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Zwinny Unik',
                'description' => 'Błyskawiczny refleks łucznika pozwalający zminimalizować siłę nadchodzących ciosów.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'buff_defense',
                'base_cooldown' => 7,
                'base_duration' => 3,
                'base_value' => 0.20,
                'scaling_value' => 0.035,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'swift-evade.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Astralna Osłona',
                'description' => 'Migocząca bariera astralnej energii pochłaniająca część obrażeń wroga.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'buff_defense',
                'is_magic' => true,
                'base_cooldown' => 7,
                'base_duration' => 3,
                'base_value' => 0.20,
                'scaling_value' => 0.035,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'astral-shield.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Boska Bariera',
                'description' => 'Święta bariera dzwonu otaczająca postać, znacząco redukująca przyjmowane obrażenia.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'buff_defense',
                'is_magic' => true,
                'base_cooldown' => 8,
                'base_duration' => 4,
                'base_value' => 0.25,
                'scaling_value' => 0.04,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'divine-barrier.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Cień Ukrycia',
                'description' => 'Skrytobójca zlewa się z cieniem, znacznie utrudniając trafienie go silnym atakiem.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'buff_defense',
                'base_cooldown' => 8,
                'base_duration' => 4,
                'base_value' => 0.25,
                'scaling_value' => 0.04,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'shadow-stealth.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Kamienna Postawa',
                'description' => 'Niezłomna, kamienna postawa bojowa dostępna dla każdej broni, drastycznie redukująca obrażenia.',
                'type' => 'active',
                'required_weapon_type' => 'all',
                'effect_type' => 'buff_defense',
                'base_cooldown' => 9,
                'base_duration' => 4,
                'base_value' => 0.35,
                'scaling_value' => 0.05,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'stone-stance.png',
                'icon' => null,
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Nieugięta Wola',
                'description' => 'Absolutna, legendarna niezłomność ducha - obrażenia wroga tracą większość swojej siły.',
                'type' => 'active',
                'required_weapon_type' => 'all',
                'effect_type' => 'buff_defense',
                'base_cooldown' => 10,
                'base_duration' => 5,
                'base_value' => 0.45,
                'scaling_value' => 0.06,
                'required_level' => 99,
                'unlock_cost' => 100,
                'icon' => 'unyielding-will.png',
                'icon' => null,
            ],
        ];

        foreach ($skills as $skill) {
            $isPassive = ($skill['type'] ?? 'active') === 'passive';
            $reqLevel = $skill['required_level'] ?? 1;

            if ($isPassive) {
                if ($reqLevel <= 15) {
                    $baseMana = 18;
                    $scalingMana = 6;
                } elseif ($reqLevel <= 30) {
                    $baseMana = 30;
                    $scalingMana = 9;
                } elseif ($reqLevel <= 50) {
                    $baseMana = 45;
                    $scalingMana = 12;
                } elseif ($reqLevel <= 70) {
                    $baseMana = 66;
                    $scalingMana = 15;
                } elseif ($reqLevel <= 90) {
                    $baseMana = 90;
                    $scalingMana = 21;
                } else {
                    $baseMana = 120;
                    $scalingMana = 30;
                }
            } else {
                if ($reqLevel <= 15) {
                    $baseMana = 36;
                    $scalingMana = 9;
                } elseif ($reqLevel <= 30) {
                    $baseMana = 66;
                    $scalingMana = 15;
                } elseif ($reqLevel <= 50) {
                    $baseMana = 114;
                    $scalingMana = 24;
                } elseif ($reqLevel <= 70) {
                    $baseMana = 165;
                    $scalingMana = 36;
                } elseif ($reqLevel <= 90) {
                    $baseMana = 240;
                    $scalingMana = 45;
                } else {
                    $baseMana = 330;
                    $scalingMana = 60;
                }
            }

            DB::table('combat_skills')->insert(array_merge($skill, [
                'base_mana_cost' => ($skill['base_mana_cost'] ?? $baseMana),
                'scaling_mana_cost' => ($skill['scaling_mana_cost'] ?? $scalingMana),
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('Seeded ' . count($skills) . ' combat skills across levels 10 to 99 with mana costs.');
    }
}
