<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CombatSkillSeeder extends Seeder
{
    public function run(): void
    {
        // Truncate or delete existing combat skills to reseed cleanly
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('character_combat_skills')->truncate();
        DB::table('combat_skills')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $skills = [
            // ==========================================
            // PRZEDZIAŁ 1: POZIOM 10 - 20 (WSTĘPNY)
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Mocny Cios',
                'description' => 'Potężne uderzenie mieczem, ignorujące część obrony. Zwiększa siłę ataku fizycznego.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 5,
                'base_duration' => 3,
                'base_value' => 0.20,
                'scaling_value' => 0.05,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'powerful-strike',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Rozłupanie',
                'description' => 'Miażdżący atak toporem o niesamowitej sile uderzenia bazowego.',
                'type' => 'active',
                'required_weapon_type' => 'axe',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 4,
                'base_duration' => 1,
                'base_value' => 1.40,
                'scaling_value' => 0.15,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'cleave-axe',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Kula Ognia',
                'description' => 'Kula czystego magmy wywołująca podpalenie celu, zadające obrażenia zależne od maksymalnego HP.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'fire',
                'base_cooldown' => 6,
                'base_duration' => 3,
                'base_value' => 0.02,
                'scaling_value' => 0.005,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'fireball',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Promień Światła',
                'description' => 'Święty błysk zaklinacza dzwonów, zadający natychmiastowe obrażenia magiczne.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 4,
                'base_duration' => 1,
                'base_value' => 1.30,
                'scaling_value' => 0.15,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'light-beam',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Trująca Strzała',
                'description' => 'Strzała powleczona jadem pająka. Zadaje obrażenia z upływem czasu równe procentowi aktualnego HP przeciwnika.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'poison',
                'base_cooldown' => 5,
                'base_duration' => 3,
                'base_value' => 0.05,
                'scaling_value' => 0.01,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'poison-arrow',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Szybkie Cięcie',
                'description' => 'Błyskawiczne pchnięcie sztyletem o niskim czasie odnowienia.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 3,
                'base_duration' => 1,
                'base_value' => 1.35,
                'scaling_value' => 0.15,
                'required_level' => 10,
                'unlock_cost' => 5,
                'icon' => 'quick-stab',
            ],

            // ==========================================
            // PRZEDZIAŁ 2: POZIOM 25 - 35 (ŚREDNI)
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Okrzyk Bojowy',
                'description' => 'Zastraszający okrzyk zwiększający siłę fizyczną bez względu na noszoną broń.',
                'type' => 'active',
                'required_weapon_type' => 'all',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 7,
                'base_duration' => 4,
                'base_value' => 0.30,
                'scaling_value' => 0.05,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'battle-cry',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Wirujący Miecz',
                'description' => 'Pełny obrót miecza zadający wysokie obrażenia bezpośrednie.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 1.80,
                'scaling_value' => 0.20,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'whirlwind-sword',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Lodowy Pocisk',
                'description' => 'Lodowy promień zamrażający cel i zadający potężne obrażenia bezpośrednie.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 1.70,
                'scaling_value' => 0.20,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'ice-bolt',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Błogosławieństwo Szamana',
                'description' => 'Rytualna pieśń zwięszająca siłę duchową i obrażenia bojowe.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 7,
                'base_duration' => 3,
                'base_value' => 0.25,
                'scaling_value' => 0.05,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'shaman-blessing',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Ognista Strzała',
                'description' => 'Płonąca strzała zadająca obrażenia na podstawie maksymalnego HP przeciwnika.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'fire',
                'base_cooldown' => 7,
                'base_duration' => 3,
                'base_value' => 0.03,
                'scaling_value' => 0.01,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'fire-arrow',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Zatruty Sztylet',
                'description' => 'Wykonywany z zaskoczenia cios zatrutym ostrzem rozlewający jad w ciele wroga.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'poison',
                'base_cooldown' => 5,
                'base_duration' => 4,
                'base_value' => 0.06,
                'scaling_value' => 0.01,
                'required_level' => 25,
                'unlock_cost' => 15,
                'icon' => 'poison-dagger',
            ],

            // ==========================================
            // PRZEDZIAŁ 3: POZIOM 45 - 55 (ZAAWANSOWANY)
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Miażdżące Cięcie',
                'description' => 'Rozpalony topór nakłada głębokie krwawienie i podpalenie na cel.',
                'type' => 'active',
                'required_weapon_type' => 'axe',
                'effect_type' => 'fire',
                'base_cooldown' => 6,
                'base_duration' => 3,
                'base_value' => 0.035,
                'scaling_value' => 0.01,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'crushing-axe',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Szarża Rycerska',
                'description' => 'Niszczycielski wypad miecza z pełną siłą rozpędu.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 2.40,
                'scaling_value' => 0.25,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'knight-charge',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Piekielny Pożar',
                'description' => 'Rozpętanie płomieni ognia piekielnego pożerającego żywotność wroga.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'fire',
                'base_cooldown' => 8,
                'base_duration' => 4,
                'base_value' => 0.045,
                'scaling_value' => 0.01,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'hellfire',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Dzwon Przeznaczenia',
                'description' => 'Rezonujący gong rozbijający pancerz i zadający krytyczne obrażenia magiczne.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 2.40,
                'scaling_value' => 0.25,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'destiny-bell',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Grad Strzał',
                'description' => 'Salwa strzał wypuszczona z niewiarygodną prędkością.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 2.30,
                'scaling_value' => 0.25,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'arrow-rain',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Cios w Plecy',
                'description' => 'Zabójcze ukłucie w czuły punkt celu z zadaniem gigantycznych obrażeń.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 4,
                'base_duration' => 1,
                'base_value' => 2.60,
                'scaling_value' => 0.30,
                'required_level' => 45,
                'unlock_cost' => 30,
                'icon' => 'backstab',
            ],

            // ==========================================
            // PRZEDZIAŁ 4: POZIOM 60 - 75 (EKSPERCJI)
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Gniew Berserkera',
                'description' => 'Wpadnięcie w szał bitewny dramatycznie zwiększający zadawane obrażenia.',
                'type' => 'active',
                'required_weapon_type' => 'axe',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 8,
                'base_duration' => 4,
                'base_value' => 0.50,
                'scaling_value' => 0.08,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'berserker-rage',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Smoczy Zamach',
                'description' => 'Cięcie nasycone smoczą energią, ignorujące defensywę przeciwnika.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 3.20,
                'scaling_value' => 0.30,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'dragon-slash',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Piorun Arcymaga',
                'description' => 'Piorun uderzający prosto z niebios w wybranego przeciwnika.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 3.30,
                'scaling_value' => 0.30,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'lightning-strike',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Święta Aura',
                'description' => 'Aura czystej mocy bojowej wzmacniająca ataki o znaczny procent.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 9,
                'base_duration' => 4,
                'base_value' => 0.50,
                'scaling_value' => 0.08,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'holy-aura',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Precyzyjny Strzał w Serce',
                'description' => 'Strzał mierzony prosto w prosto w serce z dewastującą siłą.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 3.40,
                'scaling_value' => 0.35,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'heart-shot',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Taniec Cieni',
                'description' => 'Wykonywana sekwencja mrocznych cięć podnosząca skuteczność ataku.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 7,
                'base_duration' => 3,
                'base_value' => 0.60,
                'scaling_value' => 0.10,
                'required_level' => 60,
                'unlock_cost' => 45,
                'icon' => 'shadow-dance',
            ],

            // ==========================================
            // PRZEDZIAŁ 5: POZIOM 80 - 90 (MISTRZOWSKI)
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Żelazny Bastion',
                'description' => 'Zwycięska postawa bojowa podnosząca siłę i skupienie ataku na najwyższy poziom.',
                'type' => 'active',
                'required_weapon_type' => 'all',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 9,
                'base_duration' => 5,
                'base_value' => 0.70,
                'scaling_value' => 0.10,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'iron-bastion',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Piekielne Cięcie',
                'description' => 'Atak bronią białą pozostawiający niegasnące płomienie zagłady.',
                'type' => 'active',
                'required_weapon_type' => 'sword',
                'effect_type' => 'fire',
                'base_cooldown' => 7,
                'base_duration' => 4,
                'base_value' => 0.06,
                'scaling_value' => 0.015,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'infernal-slash',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Meteoryt Mroku',
                'description' => 'Przyzwanie kosmicznego skału mroku spalającego maksymalne zdrowie wroga.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'fire',
                'base_cooldown' => 9,
                'base_duration' => 4,
                'base_value' => 0.07,
                'scaling_value' => 0.015,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'dark-meteor',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Promień Zagłady',
                'description' => 'Skupiony snop kosmicznej energii dzwonu zmiatający przeciwnika.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 4.20,
                'scaling_value' => 0.40,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'beam-doom',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Deszcz Jadowitych Strzał',
                'description' => 'Chmura jadowitych bełtów trawiąca zdrowie aktualne celów z ogromną siłą.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'poison',
                'base_cooldown' => 8,
                'base_duration' => 4,
                'base_value' => 0.12,
                'scaling_value' => 0.02,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'venom-rain',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Zabójczy Cień',
                'description' => 'Mordercze pchnięcie prosto ze świata cieni.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 5,
                'base_duration' => 1,
                'base_value' => 4.40,
                'scaling_value' => 0.45,
                'required_level' => 80,
                'unlock_cost' => 60,
                'icon' => 'fatal-shadow',
            ],

            // ==========================================
            // PRZEDZIAŁ 6: POZIOM 95 - 100 (LEGENDARNY)
            // ==========================================
            [
                'id' => Str::ulid(),
                'name' => 'Cios Rozdzierający Światy',
                'description' => 'Niewyobrażalny zamach rozcinający czasoprzestrzeń i zadający gigantyczne obrażenia.',
                'type' => 'active',
                'required_weapon_type' => 'axe',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 7,
                'base_duration' => 1,
                'base_value' => 5.50,
                'scaling_value' => 0.50,
                'required_level' => 95,
                'unlock_cost' => 80,
                'icon' => 'world-render',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Ostateczna Obrona Boska',
                'description' => 'Błogosławieństwo bogów wojny dające gigantyczny wzrost mocy bojowej.',
                'type' => 'active',
                'required_weapon_type' => 'all',
                'effect_type' => 'buff_phys_dmg',
                'base_cooldown' => 10,
                'base_duration' => 5,
                'base_value' => 1.00,
                'scaling_value' => 0.15,
                'required_level' => 95,
                'unlock_cost' => 80,
                'icon' => 'divine-bastion',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Apokalipsa Elementów',
                'description' => 'Kompletne zniszczenie żywiołami powodujące absolutne spopielenie wroga.',
                'type' => 'active',
                'required_weapon_type' => 'wand',
                'effect_type' => 'fire',
                'base_cooldown' => 10,
                'base_duration' => 5,
                'base_value' => 0.09,
                'scaling_value' => 0.02,
                'required_level' => 100,
                'unlock_cost' => 100,
                'icon' => 'elemental-apocalypse',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Boska Światłość',
                'description' => 'Pierwotne światło niszczące mrok i odparowujące przeciwnika.',
                'type' => 'active',
                'required_weapon_type' => 'bell',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 6.00,
                'scaling_value' => 0.60,
                'required_level' => 100,
                'unlock_cost' => 100,
                'icon' => 'divine-light',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Boski Strzał Arcyłowcy',
                'description' => 'Mityczny strzał ostateczny przewiercający wszystko na swojej drodze.',
                'type' => 'active',
                'required_weapon_type' => 'bow',
                'effect_type' => 'direct_dmg',
                'base_cooldown' => 6,
                'base_duration' => 1,
                'base_value' => 5.80,
                'scaling_value' => 0.55,
                'required_level' => 100,
                'unlock_cost' => 100,
                'icon' => 'god-shot',
            ],
            [
                'id' => Str::ulid(),
                'name' => 'Ostrze Pustki',
                'description' => 'Legendarne cięcie mrokiem trawiące żywotność i kwas przeciwnika z niewyobrażalną siłą.',
                'type' => 'active',
                'required_weapon_type' => 'dagger',
                'effect_type' => 'poison',
                'base_cooldown' => 7,
                'base_duration' => 5,
                'base_value' => 0.15,
                'scaling_value' => 0.025,
                'required_level' => 100,
                'unlock_cost' => 100,
                'icon' => 'void-blade',
            ],
        ];

        foreach ($skills as $skill) {
            DB::table('combat_skills')->insert(array_merge($skill, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('Seeded ' . count($skills) . ' combat skills across levels 10 to 100.');
    }
}
