<?php

namespace App\Infrastructure\Persistence;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * A short-lived, one-time code generated by "/discord" in the in-game chat,
 * used to link a Character to a Discord user account when they type
 * "!link <code>" in the bridged Discord channel.
 */
class DiscordLinkCode extends Model
{
    protected $fillable = [
        'code',
        'character_id',
        'expires_at',
    ];

    protected $casts = [
        'expires_at' => 'datetime',
    ];

    public function character(): BelongsTo
    {
        return $this->belongsTo(Character::class);
    }

    public function isExpired(): bool
    {
        return $this->expires_at->isPast();
    }
}
